### ISSUE TITLE
Impordi artiklite ja lavastuste meedia Entust

### ISSUE THREAD

**Issue by mitselek** [i-b-c/KGS#12]

**Comment by LiisKasper** [comment]
Starpis on olemas meedia ja seosed osade pareformance ja article'ga. Osad meedia failid on liiga suured Strapi jaoks, nende endu id on olemas. Samuti on osad meediad artiklitele, mida pole veel Strapis.

**Comment by LiisKasper** [comment]
Ka suured pildid saavad Strapisse. Lisaks meediale on Strapis nyyd ka performance.logos
