### ISSUE TITLE
Performance otherWorks import uuesti...

### ISSUE THREAD

**Issue by mpennaste** [i-b-c/KGS#122]
- [x] X_other_works kustutada
- [x] Teha uus komponent relatsiooniga performance'itele nimega other_works
- [x] uuesti importida, et luua relatsioonid
- [x] front'is veenduda, et kuvatud ja lingitud korrektselt

**Comment by LiisKasper** [comment]
- [x] other_works lisamisel peab relatsiooni looma ka tagasi, täidab other_works_back järgi ka other_works.
Probleem: enam kustutada ei saa, kui on kirjas other_works_back lahtris, siis save nupu vajutamisel kirjutatakse tagasi other_works lahtrisse.
Probleem2: other_works_back sisu kirjutatakse other_works sisse ainult juhul, kui vajutada save nuppu. Kui  obj.2  juurest loodi relatsioon, siis obj.1, millega seos loodi, other_works sisu ei muutu.

**Comment by mpennaste** [comment]
Done
