### ISSUE TITLE
Artikkel ja võib olla ka teised ei ilmu strapidata/{mudel}.yaml faili kui seda seal juba ees ei ole

### ISSUE THREAD

**Issue by mpennaste** [i-b-c/KGS#123]
Testitud artiklil ID'ga 142, targeted build (hetkel kui full buildi pole pärast artikli lisamist tehtud).

Võimalik, et ka teiste collectionitega sama probleem.

strapi-development/api/article/model/article.js koodis ilmneb, et läbi lähevad vaid muudatused artiklitele mille ID juba on olemas yaml failis.

St võimalik, et lahendamata on avaldamise/kustutamise juhtumid mis tuleks samuti lahendada ilma full-buildita.

**Comment by LiisKasper** [comment]
Article (ja teised) ilmuvad, kui lisada uus, Kaovad, kui kustutada. Vaja teha:
- [x] kui valida unpublish, peaks ka kaduma.
