### ISSUE TITLE
Strapis puudu event.saal-location (ENTU: Asukoht (KGS))

### ISSUE THREAD

**Issue by mpennaste** [i-b-c/KGS#22]
(Ei ole tõlgitav väli, vähemalt ENTUs praegu)

**Comment by mpennaste** [comment]
Lisaks puudu:
event.X_ticket_info.max_price (ENTUs: PL/Hind kuni)

**Comment by LiisKasper** [comment]
Starpis ja mudelis uued väljad event.X_location_et ja event.X_location_en, nende vaste entus et-location ja en-location, JA event.location millel relatsioon locationile, vaste entus on saal-location. Samuti olemas väli event.X_ticket_info.max_price
