### ISSUE TITLE
Strapis puudu/muuta

### ISSUE THREAD

**Issue by mpennaste** [i-b-c/KGS#56]
Et olemasolevat lehekülge reprodutseerida, siis vajalik järgnev või samaväärne parem lahendus:

**Event:**
- [x] **Categories puudu** (residentuuridel on, nt https://saal.entu.ee/entity/folder/6316)
- [x] Residentuuri jaoks vajalik **korratav** tekstiväli **Videos ja** korratav tekstiväli **Audios** (nt https://saal.ee/et/resident/6569 ehk https://saal.entu.ee/entity/event/6569 on mitme videoga)

**Articles (magazin, echo):**
- [x] **Video** tekstiväli peaks olema **korratav**
- [x] **Audio** tekstiväli peaks olema **korratav**

**Coverage:** #63
- [x] Peformance'ite kui festivalide (parent_event millel puudub oma performance) osas panema paika kuidas jääb. St kui tahetaks nagu praegu ENTUs, festivali ehk eventi külge selle kohta käiv coverage lisada, siis hetkel seda otse teha ei saa. Saaks lisada vaid selle festivali child_event'i performance külge, aga siis oleks see seotud ka selle performance'iga (mis ei pruugi kajastuse sisu olla, kajastus äkki laiemalt kogu festivali kohta). Vajab mõtlemist.
Nt festivali coverage: https://saal.ee/et/festival/5937/press

**Comment by mitselek** [comment]
Teeks nii nagu nad praegugi harjunud on:
Pressikajastusi saab lisada nii sündmustele kui lavastustele;
Lavastuse kuvamisel näidatakse kõiki nii selle lavastuse kui ka sündmuse kajastusi.

**Comment by mitselek** [comment]
Entust eksporditakse nüüd iga objekti juurde ka tema lapsed
