### ISSUE TITLE
Erinevused ja puudused võrreldes praeguse Saali lehega

### ISSUE THREAD

**Issue by mpennaste** [i-b-c/KGS#59]
**NB! Kõrvutage main haru serveeritavat ja live kodulehte ning lisage julgelt allolevale lisaks!**

Hetkel teadaolevad puudused:
- [x] Labelid - hetkel enamik _hard-coded_ ja Strapis pigem igasuguseid ebamääraseid, üleliigseid jne. Vajalik korrastada Strapis, eemaldada üleliigsed, vajadusel luua uusi label-gruppe ja labeleid.
- [x] Festivali programmi JS ("täna" jms tekstid kuvamiseks)
- [x] JSON avalehe JS kalendri tarbeks (https://saal.ee/et/calendar_json) #61 
- [x] Avaleht - tuurid JS, residentuurid + JS
- [x] Piletiostu lingid erinevatel lehtedel
- [x] Festival->Press - Coverage teema (issue #56 )
- [x] Performance - coverage (ibid)
- [x] Event (resident) - categories (ibid)
- [x] Articles - korratav audio & video (ibid)
- [x] Build kataloog ja selle tuhat faili, et kasu seda häirivat asja kompenseeriks, oleks tore staging alamdomeeni tööle saada. Pigem oleks tore build kataloog gitignore faili lisada ja nt script teha mis siis vajadusel kopeeriks selle kataloogi mida kavatseme GH "hostingus" kuvada, et iga kord ei peaks kõiki neid faile commitima ja oleks lihtsam omi muudatusi tööfailides jälgida. @mitselek

**Comment by mitselek** [comment]
main harus on build juba gitignore's. sorry, et **jälle** müra tekitasin

**Comment by mpennaste** [comment]
> main harus on build juba gitignore's. sorry, et **jälle** müra tekitasin

Hmm, vaatasin, et ikka pole, aga lisasin nüüd, no problemo 👍
