### ISSUE TITLE
Taastada Strapi collection collection types menüüvaade 

### ISSUE THREAD

**Issue by mpennaste** [i-b-c/KGS#74]
Strapi Admin paneelis vaate max-height kõrgemaks sel osal ja võib olla kõigil margin-bottom väiksemaks.
![strapiadminpanelview](https://user-images.githubusercontent.com/68708892/103689933-a401b580-4f9c-11eb-89b9-b11ad0bc5929.png)

Strapi uuendamine taastas algse  olukorra.

**Comment by SiimS1** [comment]
Done - https://strapi.io/documentation/developer-docs/latest/admin-panel/customization.html#styles
