### ISSUE TITLE
HTML-i lubavate väljade valideerimine strapist tirimise ajal

### ISSUE THREAD

**Issue by marianntapfer** [i-b-c/KGS#76]
5059 - video link sulgemata tag-idea

**Comment by mpennaste** [comment]
Strapi backis audio ja video lisades:

`var HTMLParser = require('node-html-parser');

let content = 'HTML SIIA'

var root = HTMLParser.parse(content);

console.log(root.toString());`

**Comment by mpennaste** [comment]
`<iframe src="https://player.vimeo.com/video/221570775" width="100%" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/221570775"`

**Comment by mpennaste** [comment]
`<iframe src="https://player.vimeo.com/video/221570775" width="100%" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/221570775"`

**Comment by mpennaste** [comment]
```
<iframe src="https://player.vimeo.com/video/221570775" width="100%" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/221570775"
```

**Comment by mpennaste** [comment]
@SiimS1 
1601 Peformance sulgemata tagidega triggerdab ENTU poolt errori:
`2021-02-15T00:27:28.243Z - 00:02:42 - 467 - 0.35s - \_fetchdir\performances\1597
2021-02-15T00:27:28.632Z - 00:02:42 - 466 - 0.35s - \_fetchdir\performances\1598
2021-02-15T00:27:28.935Z - 00:02:41 - 465 - 0.35s - \_fetchdir\performances\1599

ERROR:
C:\dev2\KGS\source\_fetchdir\performances\1601\index.pug
Parse Error:

**Comment by mpennaste** [comment]
Manuaalselt Strapis 1601 Peformance parandatud
Eelnevalt oli:
`<p><a href="https://vimeo.com/221570775"`

**Comment by SiimS1** [comment]
Done. Added for article, event, performance api/models:
var HTMLparser = require('node-html-parser')

if (data.audios) {
        let counter = 0
        for (let audio of data.audios) {
          counter++
          if (!HTMLparser.valid(audio.content)) {
            throw strapi.errors.badRequest("Can't save, audio " + counter + " html invalid!")
          }
        }
      }
      if (data.videos) {
        let counter = 0
        for (let video of data.videos) {
          counter++
          if (!HTMLparser.valid(video.content)) {
            throw strapi.errors.badRequest("Can't save, video " + counter + " html invalid!")
          }
        }
      }
